### PR TITLE
Newer iframe and pframe format

### LINKED ISSUE #226: Deserialization/Parsing Error with RLC-810A
**Describe the bug**
Connecting to an RLC-810A using Docker image fails to parse.

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create docker-compose.yaml:
```
version: "2"
services:
  neolink:
    image: thirtythreeforty/neolink
    container_name: neolink
    ports:
      - 8554:8554
    volumes:
      - /docker/data/neolink/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
    environment:
      RUST_LOG: "debug"
      GST_DEBUG: 3
```
2. Create neolink.toml:
```
bind = "0.0.0.0"
[[cameras]]
name = "outdoor"
username = "viewer"
password = "XXXXX"
address = "10.20.0.91:9000"
stream = "mainStream"
```
3. Pull/start: 
`docker-compose up -d`

**Expected behavior**
Working RTSP stream.

**Versions**
Neolink software: 0.4.0?
Reolink camera model and firmware: RLC-810A IPC_523128M8MP v3.0.0.494_21073003

**Logs**
```
[2021-11-11T18:52:34Z INFO  neolink] Neolink 0.4.0 (unknown commit) release
0:00:00.229758305 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x120000: 'AVR (Audio Visual Research)' is not mapped
0:00:00.229812778 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x180000: 'CAF (Apple Core Audio File)' is not mapped
0:00:00.229836432 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x100000: 'HTK (HMM Tool Kit)' is not mapped
0:00:00.229863321 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
0:00:00.229886762 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
0:00:00.229909837 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x210000: 'MPC (Akai MPC 2k)' is not mapped
0:00:00.229934434 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
0:00:00.230045782 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x160000: 'SD2 (Sound Designer II)' is not mapped
0:00:00.230161896 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00;04m             default gstsf.c:97:gst_sf_create_audio_template_caps:[00m format 0x190000: 'WVE (Psion Series 3)' is not mapped
0:00:00.256190496 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00m             nvcodec gstcudaloader.c:114:gst_cuda_load_library:[00m Could not open library libcuda.so.1, Error loading shared library libcuda.so.1: No such file or directory
0:00:00.256240966 [33m    8[00m 0x7f8d883178c0 [33;01mWARN   [00m [00m             nvcodec plugin.c:66:plugin_init:[00m Failed to load cuda library
[2021-11-11T18:52:35Z DEBUG neolink::rtsp::gst] Permitting anonymous to access /outdoor, /outdoor/mainStream
[2021-11-11T18:52:35Z DEBUG neolink_core::bc_protocol] Trying address 10.20.0.91:9000
[2021-11-11T18:52:35Z DEBUG neolink_core::bc_protocol] Success
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Connecting to camera at Address: 10.20.0.91:9000
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Logging in
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "body"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(body, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "Encryption"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(Encryption, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(md5)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(nonce, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(618d6673-zM5timDtSiWWj0ntBxrT)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(nonce)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(Encryption)
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "body"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(body, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "DeviceInfo"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(DeviceInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(firmVersion, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(00000000983040)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(firmVersion)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(IOInputPortNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(IOInputPortNum)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(IOOutputPortNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(IOOutputPortNum)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(diskNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(diskNum)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(ipc)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(channelNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(channelNum)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(audioNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(audioNum)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(ipChannel, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(ipChannel)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(analogChnNum, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(analogChnNum)
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "resolution"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolutionName, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(3840*2160)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolutionName)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(3840)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2160)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(language, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(English)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(language)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(sdCard, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(sdCard)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(ptzMode, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(none)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(ptzMode)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(typeInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(IPC)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(typeInfo)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(softVer, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(50332142)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(softVer)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hardVer, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hardVer)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(panelVer, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(panelVer)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hdChannel1, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hdChannel1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hdChannel2, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hdChannel2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hdChannel3, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hdChannel3)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hdChannel4, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hdChannel4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(norm, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(NTSC)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(norm)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(osdFormat, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(MDY)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(osdFormat)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(B485, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(B485)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(supportAutoUpdate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(supportAutoUpdate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(userVer, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(userVer)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(FrameworkVer, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(FrameworkVer)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(secretCode, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0000000089f1ddf2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(secretCode)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(authMode, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(authMode)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(DeviceInfo)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(StreamInfoList, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(StreamInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(channelBits, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(channelBits)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(mainStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(3840)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2160)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(6144)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25,22,20,18,16,15,12,10,8,6,4,2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(4096,5120,6144,7168,8192)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(subStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(640)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(360)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(10)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(256)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(15,10,7,4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(64,128,160,192,256,384,512)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(StreamInfo)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(StreamInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(channelBits, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(channelBits)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(mainStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2560)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1440)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(6144)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25,22,20,18,16,15,12,10,8,6,4,2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1024,1536,2048,3072,4096,5120,6144,7168,8192)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(subStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(640)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(360)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(10)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(256)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(15,10,7,4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(64,128,160,192,256,384,512)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(StreamInfo)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(StreamInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(channelBits, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(channelBits)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(mainStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2304)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1296)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(6144)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(25,22,20,18,16,15,12,10,8,6,4,2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1024,1536,2048,3072,4096,5120,6144,7168,8192)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(encodeTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(subStream)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(resolution, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(width, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(640)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(width)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(height, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(360)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(height)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(resolution)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultFramerate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(10)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultFramerate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultBitrate, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(256)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultBitrate)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(framerateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(15,10,7,4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(framerateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(bitrateTable, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(64,128,160,192,256,384,512)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(bitrateTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(defaultGop, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(4)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(defaultGop)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(encodeTable)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(StreamInfo)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(StreamInfoList)
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Connected and logged in
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "body"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(body, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "SystemGeneral"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(SystemGeneral, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(timeZone, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(18000)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(timeZone)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(osdFormat, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(MDY)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(osdFormat)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(year, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(2021)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(year)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(month, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(11)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(month)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(day, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(11)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(day)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hour, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(13)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hour)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(minute, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(52)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(minute)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(second, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(35)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(second)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(deviceId, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(deviceId)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(timeFormat, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(timeFormat)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(language, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(English)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(language)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(deviceName, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(TestingCam1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(deviceName)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(SystemGeneral)
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "Norm"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(Norm, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(norm, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(NTSC)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(norm)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(Norm)
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Camera time is already set: 2021-11-11 13:52:35 -5
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "body"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(body, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "VersionInfo"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(VersionInfo, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(name, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(TestingCam1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(name)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(type, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(RLC-810A)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(type)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(serialNumber, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(00000000983040)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(serialNumber)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(buildDay, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(build 21073003)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(buildDay)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(hardwareVersion, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(IPC_523128M8MP)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(hardwareVersion)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(cfgVersion, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(v3.0.0.0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(cfgVersion)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(firmwareVersion, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(v3.0.0.494_21073003)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(firmwareVersion)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(detail, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(IPC_523128M8MPS18E1W01100000001)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(detail)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(IEClient, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(IEClient)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(IEClient)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(pakSuffix, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(pak)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(pakSuffix)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(helpVersion, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(blackPointsLevel=0)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(helpVersion)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(VersionInfo)
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Camera reports firmware version v3.0.0.494_21073003
[2021-11-11T18:52:35Z INFO  neolink::rtsp] outdoor: Starting video stream Main Stream (Clear)
[2021-11-11T18:52:35Z DEBUG neolink_core::bc::xml] Struct: start to parse "Extension"
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(Extension, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched StartElement(binaryData, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched Characters(1)
[2021-11-11T18:52:35Z DEBUG yaserde::de] Fetched EndElement(binaryData)
[2021-11-11T18:52:35Z DEBUG neolink_core::bc_protocol] Dropping camera
[2021-11-11T18:52:35Z DEBUG neolink_core::bc_protocol::connection::bcconn] Shutting down BcConnection...
[2021-11-11T18:52:35Z DEBUG neolink_core::bc_protocol::connection::bcconn] Shutdown finished OK
[2021-11-11T18:52:35Z ERROR neolink::rtsp] Error streaming from camera outdoor, will retry in 1s: Error while streaming outdoor
    
    Caused by:
        0: Media Deserialization error
        1: Parsing error
```

### LINKED ISSUE #230: Support B500 ip camera?
Hi! 

I have B500 cameras. MainStream does not work no image connected to rtsp stream but no image. subStream, on the other hand, has an image.
Is there a solution for this or isn't this camera supported?

I'm running in Docker:
   Caused by:

        0: Media Deserialization error

        1: Parsing error

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Connecting to camera at Address: x.x.x.x:9000

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Logging in

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Connected and logged in

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Camera time is already set: 2021-11-20 16:25:36 +1

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Camera reports firmware version v3.0.0.108_20092314

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Starting video stream Main Stream (Clear)

config:

 bind = "0.0.0.0"
 
 [[cameras]]
 name = "test"
 username = "user"
 password = "xxxx"
 address = "x.x.x.x:9000"
 stream = "subStream"
 format = "H264"

Thank you very much for your reply!

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This updates the iframe and pframe to use the newer format, detailed discussions about it is #237

To summarise:

It was discovered that in the header

| magic | type | size | unknown A | ms | unknown B | time | unknown C |
|:------:|:----:|:-----:|:--------:|:---:|:---------:|:-----:|:---------:|
| 30306463 | 48323634 | A3820B00 | 08000000 | C015D29D | 0A000000 | 1DAE1B61 | 0F00C300 |

Unknown A is actuall a header size extension. Old packets had a fixed size  but newer packets have differnt header sizes with additional info based on the need.

This PR enabled the bcmedia deser to handle this variable header size

Fix #230
Fix #226

### CODE REVIEW

**Review by pmwoodward3 — DISMISSED** [review]

File: crates/core/src/bcmedia/de.rs [hunk 1]
```diff
@@ -240,11 +240,41 @@ fn bcmedia_iframe(buf: &[u8]) -> IResult<&[u8], BcMediaIframe> {
...
+    } else {
+        (buf, None)
+    };
+    let (buf, _unknown_remained) = if additional_header_size > 16 {
+        let remainder = additional_header_size - 16;
+        let (buf, unknown_remained) = take!(buf, remainder)?;
+        (buf, Some(unknown_remained))
+    } else {
+        (buf, None)
+    };
```
Comment (thirtythreeforty) [inline crates/core/src/bcmedia/de.rs:276]: Why does this have extra `_unknown_[b-e]` fields? Can you just collapse them directly into `unknown_remained`?

Comment (QuantumEntangledAndy) [reply crates/core/src/bcmedia/de.rs:258]: Ok Done. Was mostly for some testing.

p.s. Nice to hear from you, how are things?

**Review by thirtythreeforty — APPROVED** [review]
